services:
  web:
    build: .
    ports:
      - '5000:5000'
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/productdb
      - FLASK_APP=main.py
      - FLASK_ENV=development
      - FLASK_DEBUG=True
      - SECRET_KEY=your-secret-key-here
    volumes:
      - .:/app
    depends_on:
      - db
    networks:
      - product-network

  db:
    image: postgres:13
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=productdb
    ports:
      - '5433:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - product-network

volumes:
  postgres_data:

networks:
  product-network:
    driver: bridge
